#!/usr/bin/env bash
# Update package list and install Nginx
apt update
apt install nginx -y

# Configure Nginx to perform the redirection
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /etc/nginx/html;
    index index.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}' > /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
