#!/usr/bin/env bash
# Update package list and install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx to perform the redirection using sed
sed -i '/listen \[::\]:80 default_server;/a
    
    location \/redirect_me \{
        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;
    \}
' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart

