#!/usr/bin/env bash
# Update package list and install Nginx
apt update
apt install -y nginx

# Create the Nginx configuration file
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        return 200 "Hello World!\n";
    }

    location /redirect_me {
        return 301 https://github.com/amine-zzr;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOF

# Create custom 404 HTML page
printf "Ceci n'est pas une page\n" > /var/www/html/404.html

# Restart Nginx to apply changes
service nginx restart
