#!/usr/bin/env bash
# Update package list and install Nginx
apt update
apt install nginx -y

# Configure Nginx to listen on port 80 and return "Hello World!"
printf "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html;

        location / {
                return 404 "Ceci n\'est pas une page\n";
        }

        error_page 404 /404.html;
        location = /404.html {
                root /var/www/html;
                internal;
        }


        location / {
                return 200 "Hello World!\n";
        }
}" > /etc/nginx/sites-available/default

replacement="index index.html;\n\trewrite ^\/redirect_me https:\/\/github.com\/amine-zzr permanent;"
sed -i "s/index index.html;/$replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" > /var/www/html/404.html

#Restart Nginx to apply changes
service nginx restart
