#!/usr/bin/env bash
# Set the permissions of nginx.conf to 644
sudo chmod 644 /etc/nginx/nginx.conf

# Change the ownership of the nginx server directory to nginx user
sudo chown -R nginx:nginx /etc/nginx

# Change the nginx user in the configuration file
sudo sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf

# Change the port to 8080 in the configuration file
sudo sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-enabled/default

# Kill apache2 process
sudo pkill apache2

# Restart nginx
sudo -u nginx service nginx restart
