#!/usr/bin/env bash
# Debugging a server
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf 
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo pkill apache2
sudo -u nginx service nginx restart
