#!/usr/bin/env bash
# Get the PID of the Gunicorn master process
GUNICORN_PID=$(pgrep -f 'gunicorn --workers' | head -n 1)

if [ -n "$GUNICORN_PID" ]; then
  # Send SIGHUP signal to the Gunicorn master process to reload gracefully
  kill -HUP "$GUNICORN_PID"
  echo "Gunicorn master process with PID $GUNICORN_PID has been sent SIGHUP signal to reload gracefully."
else
  echo "Gunicorn master process not found."
fi
